version: 2

jobs:
  build:
    steps:
      - checkout
      - run: echo BUILD
  deploy:
    steps:
      - checkout
      - run: echo DEPLOY

workflows:
  version: 2
  jobs:
    - build:
    - deploy:
        requires:
          - build
        filters:
          tags:
            only: /[0-9]+(\.[0-9+])*/
