version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: echo BUILD

#  deploy:
#    docker:
#      - image: circleci/golang:1.9
#    steps:
#      - checkout
#      - run: echo DEPLOY

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /[0-9]+\..*/
              #only: /[0-9]+(\.[0-9+])*/

#    - deploy:
#        requires:
#          - build
#        filters:
#          tags:
#            only: /[0-9]+/
