version: 2

jobs:
  build:
    docker:
      - image: circleci/golang:1.9
    steps:
      - checkout
      - run: echo BUILD
      - run: echo x${CIRCLE_TAG}x

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /[0-9]+(\.[0-9+])*/
